#!/usr/bin/sh

DOTFILES_GIT_DIR=$HOME/.config/.dotfilesTEST
DOTFILES_BACKUP_DIR=$DOTFILES_GIT_DIR/backup

rm -rf $DOTFILES_GIT_DIR

git clone --bare \
    https://www.github.com/lnfiniteMonkeys/dotfiles.git \
    $DOTFILES_GIT_DIR

alias dotfiles="git --git-dir=$DOTFILES_GIT_DIR --work-tree=$HOME"


dotfiles checkout
if [ $? = 0 ]; then
    echo "Checked out dotfiles.";
else
    echo "Pre-existing dotfiles found, backupng them up at" $DOTFILES_BACKUP_DIR
    FILES_TO_MOVE= config checkout 2>&1 | egrep "\s" | awk {'print $1'}
    echo $FILES_TO_MOVE
fi;


#config checkout
#config config status.showUntrackedFiles no
