method = 'copy'
plugin_dirs = [
    '/home/w1n5t0n/.wine/drive_c/Program Files/Common Files/VST3',
    '/home/w1n5t0n/.wine/drive_c/Program Files/VstPlugins',
]
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-7.5'
yabridge_host_hash = -2632122937381520262
