plugin_dirs = [
    '/home/w1n5t0n/.wine/drive_c/Program Files/Common Files/VST3',
    '/home/w1n5t0n/.wine/drive_c/Program Files/VstPlugins',
    '/home/w1n5t0n/.wine/drive_c/VSTs/32',
    '/home/w1n5t0n/.wine/drive_c/VSTs/64',
    '/home/w1n5t0n/VSTs/Windows',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-7.18 (Staging)'
yabridge_host_hash = -3094479323878875900
