#!/bin/sh

# Set keyboard languages
setxkbmap -model pc105 -layout us,gr -variant 'dvorak,simple' -option grp:alt_shift_toggle

# Swap caps and esc
#xmodmap -e "keycode 66 = Escape"
#xmodmap -e "keycode 9 = Caps_Lock"

