#!/usr/bin/env sh
PKGLIST_DIR="$PACKAGE_CONFIG_DIR/$1"
# ensure directory exists
# mkdir -p $OUTPUT_PATH


# arch
ARCH="$PKGLIST_DIR/arch_packages.txt"
sudo pacman -Syu --needed - < $ARCH
# aur
YAY="$PKGLIST_DIR/aur_packages.txt"
yay -Syu --needed - < $YAY
# TODO flatpak
# TODO snap
