import = ["/home/w1n5t0n/.config/alacritty/colors.toml", "/home/w1n5t0n/.config/alacritty/keyboard.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 150

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 11.5

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
Default = ["(macOS) Menlo", "(Linux/BSD) monospace", "(Windows) Consolas"]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1.0
title = "Terminal"
